eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.8.10:8761/eureka/
      
server:
  port: 8763
  
spring:
  application:
    name: eshop_price_service
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    url: jdbc:mysql://192.168.8.10:3306/roncoo_eshop
    username: root
    password: Pyl123456