#自定义配置，注意冒号后的空格
rsb:
  secret: ${random.value}
  number: ${random.int}
  name: www.qq.com
  desc: ${rsb.name} is a domain name

#默认加载classpath:logback-spring.xml
#不要使用logback.xml
#自定义配置
logging:
  config: classpath:logback-spring.xml

#Properties配置多环境，需要添加多个配置文件，YAML只需要一个文件
#YAML不能通过@PropertySource注解加载
#如果需要使用@PropertySource注解加载配置项值，使用Properties

#设置生效的配置文件
#java -jar xxx.jar --spring.profiles.active=dev更加灵活
spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Chongqing
  datasource:
    url: jdbc:mysql://localhost:3306/roncoo_spring_boot?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Pyl123456
  jpa:
    hibernate:
      #create 先drop已存在的表，再创建1个空表
      #create-drop 应用停止会删除表
      #update 如果表中已存在数据，不会创建新表
      #validate 验证类属性与表字段是否一致
      ddl-auto: update
    show-sql: true
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    pool:
      max-active: 8
      max-idle: 8
      #不指定配置文件启动
      #redis-server &
      #采用默认配置，无密码
      #password:
    activemq:
      in-memory: true

---
spring:
  profiles: dev

server:
  port: 8080

---
spring:
  profiles: test

server:
  port: 8081

---
spring:
  profiles: prod

server:
  port: 8082