#自定义配置，注意冒号后的空格
rsb:
  secret: ${random.value}
  number: ${random.int}
  name: www.qq.com
  desc: ${rsb.name} is a domain name

#默认加载classpath:logback-spring.xml
#不要使用logback.xml
#自定义配置
logging:
  config: classpath:logback-spring.xml

#Properties配置多环境，需要添加多个配置文件，YAML只需要一个文件
#YAML不能通过@PropertySource注解加载
#如果需要使用@PropertySource注解加载配置项值，使用Properties

#设置生效的配置文件
#java -jar xxx.jar --spring.profiles.active=dev更加灵活
spring:
  profiles:
    active: test
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Chongqing

---
spring:
  profiles: dev

server:
  port: 8080

---
spring:
  profiles: test

server:
  port: 8081

---
spring:
  profiles: prod

server:
  port: 8082